version : '3'
services:
  flask:
    container_name: flask
    image: "flask:test"
    build: ./flask
    ports: 
      - "5000:5000"
    networks:
      - backend
  nginx:
    container_name: nginx
    image: "nginx:test"
    ports:
      - "80:80"
    build: ./nginx  
    networks:
      - backend
networks:
  backend:
    driver: bridge              